name: Flutter SDK - Build/Analyze/Test/Tag

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter --version
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter build apk --release
        working-directory: example
      - id: read-version
        uses: NiklasLehnfeld/flutter-version-number-action@main
      - name: Append version suffix
        run: echo "BUILD_VERSION=${{steps.read-version.outputs.version-number}}-${GITHUB_REF_NAME}.${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
      - name: Output flutter version
        run: echo 'version_number:' ${{ ENV.BUILD_VERSION }}
      - run: git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com" && git config --global user.name "$GITHUB_ACTOR"
      - run: git tag -a v${{ ENV.BUILD_VERSION }} -m "Tagging v${{ ENV.BUILD_VERSION }}"
      - run: git push --tags && git push